import type { Metadata } from "next";
import SessionProdiver from "@/components/providers/session-prodiver";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/authOptions";
import "primereact/resources/themes/lara-light-indigo/theme.css"; //theme
import "primereact/resources/primereact.min.css"; //core css
import "primeicons/primeicons.css"; //icons
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className="h-screen">
        <SessionProdiver session={session}>{children}</SessionProdiver>
      </body>
    </html>
  );
}
